import {Footer} from './Footer.js';
import {Header} from './Header/header.js';
import {Navbar} from './Navbar.js';
import {Sidebar} from './Sidebar.js';
import {Work} from './Work/work.js';
import {Palmdrive} from './Work/palmdrive.js';
import {GraphicDesign} from './Work/graphicDesign.js';
import {Transaction} from './Work/transaction.js';
import {About} from './About/about.js';
import {Resume} from './Resume/resume.js';

export {Resume};
export {About};
export {Work};
export {Footer};
export {Header};
export {Navbar};
export {Sidebar};
export {Palmdrive};
export {Transaction};
export {GraphicDesign};
